/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd.Interfaz;

import java.io.File;
import proyecto1edd.GestorCSV;
import proyecto1edd.Hash;
import proyecto1edd.Neuro.Grafo;

/**
 *
 * @author LuchoPC
 */
public class Cargar_Csv extends javax.swing.JFrame {

    static Grafo grafo;
    static Hash hash;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cargar_Csv.class.getName());

    /**
     * Creates new form Cargar_Csv
     */
    public Cargar_Csv(Grafo grafo, Hash hash) {
        initComponents();
        this.grafo = grafo;
        this.hash = hash;
        this.setVisible(true);
        try {
            this.jTextArea1.setText(grafo.mostrar());
        }catch(Exception e){
            System.out.print("no hay grafo cargado");
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarCSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        atras = new javax.swing.JButton();
        GuardarCSV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargarCSV.setBackground(new java.awt.Color(13, 110, 253));
        CargarCSV.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        CargarCSV.setForeground(new java.awt.Color(255, 255, 255));
        CargarCSV.setText("CARGAR");
        CargarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarCSVActionPerformed(evt);
            }
        });
        jPanel1.add(CargarCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 300, 570));

        atras.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        atras.setForeground(new java.awt.Color(33, 37, 41));
        atras.setText("ATRAS");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 110, 50));

        GuardarCSV.setBackground(new java.awt.Color(13, 110, 253));
        GuardarCSV.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        GuardarCSV.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCSV.setText("GUARDAR CSV");
        GuardarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCSVActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 760, 140, 40));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("GUARDAR CSV ACTUALIZADO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 720, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("CARGAR CSV");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        MenuPrincipal m = new MenuPrincipal(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void CargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarCSVActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();

        // 2. Filtro para que solo se vean archivos .csv
        javax.swing.filechooser.FileNameExtensionFilter filtro
                = new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV", "csv");
        selector.setFileFilter(filtro);

        // 3. Abrir la ventana
        int resultado = selector.showOpenDialog(this);

        // 4. Si el usuario acepta, llamamos al lector
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = selector.getSelectedFile();
            grafo = new Grafo();
            GestorCSV c = new GestorCSV();
            c.leerArchivo(archivoSeleccionado, grafo);
            this.jTextArea1.setText(grafo.mostrar());
        }
    }//GEN-LAST:event_CargarCSVActionPerformed

    private void GuardarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCSVActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();

        // 2. Filtro para que solo se vean archivos .csv
        javax.swing.filechooser.FileNameExtensionFilter filtro
                = new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV", "csv");
        selector.setFileFilter(filtro);

        // 3. Abrir la ventana
        int resultado = selector.showOpenDialog(this);

        // 4. Si el usuario acepta, llamamos al lector
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = selector.getSelectedFile();
            GestorCSV c = new GestorCSV();
            c.guardarArchivo(archivoSeleccionado, grafo);
        }

    }//GEN-LAST:event_GuardarCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cargar_Csv(grafo, hash).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarCSV;
    private javax.swing.JButton GuardarCSV;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
