/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd.Interfaz;

import proyecto1edd.Hash;
import proyecto1edd.Neuro.Grafo;

/**
 *
 * @author LuchoPC
 */
public class Dijkstra extends javax.swing.JFrame {
    static Grafo grafo;
    static Hash hash;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dijkstra.class.getName());

    /**
     * Creates new form Dijkstra
     */
    public Dijkstra(Grafo grafo, Hash hash) {
        initComponents();
        this.setVisible(true);
        this.grafo = grafo;
        this.hash = hash;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dijkstra = new javax.swing.JButton();
        ATRAS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        destino = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        origen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dijkstra.setBackground(new java.awt.Color(13, 110, 253));
        dijkstra.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        dijkstra.setForeground(new java.awt.Color(255, 255, 255));
        dijkstra.setText("CARGAR DIJKSTRA");
        dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijkstraActionPerformed(evt);
            }
        });
        jPanel1.add(dijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, 60));

        ATRAS.setBackground(new java.awt.Color(13, 110, 253));
        ATRAS.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ATRAS.setForeground(new java.awt.Color(255, 255, 255));
        ATRAS.setText("ATRAS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });
        jPanel1.add(ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 100, 60));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel3.setText("BUSQUEDA DE RUTA MAS CORTA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane3.setViewportView(salida);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 420, 250));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("NEURONA DE ORIGEN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("NEURONA DE DESTINO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        destino.setColumns(20);
        destino.setRows(5);
        jScrollPane4.setViewportView(destino);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        origen.setColumns(20);
        origen.setRows(5);
        jScrollPane5.setViewportView(origen);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        // TODO add your handling code here:
        MenuPrincipal m = new MenuPrincipal(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_ATRASActionPerformed

    private void dijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijkstraActionPerformed
        // TODO add your handling code here:
        this.salida.setText(this.grafo.dijkstra(Integer.parseInt(this.origen.getText()),Integer.parseInt(this.destino.getText()), hash));
    }//GEN-LAST:event_dijkstraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dijkstra(grafo, hash).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JTextArea destino;
    private javax.swing.JButton dijkstra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea origen;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
