/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd.Interfaz;

import proyecto1edd.Hash;
import static proyecto1edd.Interfaz.Cargar_Csv.grafo;
import static proyecto1edd.Interfaz.Cargar_Csv.hash;
import proyecto1edd.Neuro.Grafo;

/**
 *
 * @author LuchoPC
 */
public class MenuPrincipal extends javax.swing.JFrame {

    static Grafo grafo;
    static Hash hash;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Grafo grafo, Hash hash) {
        initComponents();
        this.setVisible(true);
        this.grafo = grafo;
        this.hash = hash;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cargar = new javax.swing.JButton();
        MostrarGrafo = new javax.swing.JButton();
        MostrarHash = new javax.swing.JButton();
        Mostrar_DFS_BFS = new javax.swing.JButton();
        Dijkstra = new javax.swing.JButton();
        agregar_eliminar = new javax.swing.JButton();
        SimulacionDeFatiga = new javax.swing.JButton();
        Creacion_sinapsis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Neurotrasmisor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cargar.setBackground(new java.awt.Color(13, 110, 253));
        Cargar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Cargar.setForeground(new java.awt.Color(255, 255, 255));
        Cargar.setText("CARGAR CSV");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        jPanel1.add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, 80));

        MostrarGrafo.setBackground(new java.awt.Color(13, 110, 253));
        MostrarGrafo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        MostrarGrafo.setForeground(new java.awt.Color(255, 255, 255));
        MostrarGrafo.setText("MOSTRAR GRAFO");
        MostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, 80));

        MostrarHash.setBackground(new java.awt.Color(13, 110, 253));
        MostrarHash.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        MostrarHash.setForeground(new java.awt.Color(255, 255, 255));
        MostrarHash.setText("MOSTRAR HASHTABLE");
        MostrarHash.setBorder(null);
        MostrarHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarHashActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 190, 80));

        Mostrar_DFS_BFS.setBackground(new java.awt.Color(13, 110, 253));
        Mostrar_DFS_BFS.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Mostrar_DFS_BFS.setForeground(new java.awt.Color(255, 255, 255));
        Mostrar_DFS_BFS.setText("DFS Y BFS");
        Mostrar_DFS_BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_DFS_BFSActionPerformed(evt);
            }
        });
        jPanel1.add(Mostrar_DFS_BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, 80));

        Dijkstra.setBackground(new java.awt.Color(13, 110, 253));
        Dijkstra.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Dijkstra.setForeground(new java.awt.Color(255, 255, 255));
        Dijkstra.setText("DIJKSTRA");
        Dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DijkstraActionPerformed(evt);
            }
        });
        jPanel1.add(Dijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 80));

        agregar_eliminar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        agregar_eliminar.setText("AGG Y ELIM \n NEURONA");
        agregar_eliminar.setActionCommand("AGG Y ELIM NEURONA");
        agregar_eliminar.setBorder(null);
        agregar_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 190, 80));

        SimulacionDeFatiga.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        SimulacionDeFatiga.setText("SIMULACION DE FATIGA");
        SimulacionDeFatiga.setBorder(null);
        SimulacionDeFatiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulacionDeFatigaActionPerformed(evt);
            }
        });
        jPanel1.add(SimulacionDeFatiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 80));

        Creacion_sinapsis.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Creacion_sinapsis.setText("CREAR SINAPSIS");
        Creacion_sinapsis.setBorder(null);
        Creacion_sinapsis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Creacion_sinapsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Creacion_sinapsisActionPerformed(evt);
            }
        });
        jPanel1.add(Creacion_sinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, 80));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        Neurotrasmisor.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Neurotrasmisor.setText("AGREGAR NEUROTRASNMISOR");
        Neurotrasmisor.setBorder(null);
        Neurotrasmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeurotrasmisorActionPerformed(evt);
            }
        });
        jPanel1.add(Neurotrasmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 190, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mostrar_DFS_BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_DFS_BFSActionPerformed
        // TODO add your handling code here:
        DFS_BFS dbfs = new DFS_BFS(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_Mostrar_DFS_BFSActionPerformed

    private void MostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafoActionPerformed
        // TODO add your handling code here:
        MostrarGrafo m = new MostrarGrafo(grafo, hash);
        this.dispose();

    }//GEN-LAST:event_MostrarGrafoActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        Cargar_Csv c = new Cargar_Csv(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_CargarActionPerformed

    private void MostrarHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarHashActionPerformed
        // TODO add your handling code here:
        MostarHash h = new MostarHash(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_MostrarHashActionPerformed

    private void SimulacionDeFatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionDeFatigaActionPerformed
        // TODO add your handling code here:
        Simulacion_fatiga sf = new Simulacion_fatiga(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_SimulacionDeFatigaActionPerformed

    private void Creacion_sinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Creacion_sinapsisActionPerformed
        // TODO add your handling code here:
        Crear_sinapsis cs = new Crear_sinapsis(grafo, hash);
        this.dispose();

    }//GEN-LAST:event_Creacion_sinapsisActionPerformed

    private void agregar_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_eliminarActionPerformed
        // TODO add your handling code here:
        Agregar a = new Agregar(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_agregar_eliminarActionPerformed

    private void DijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DijkstraActionPerformed
        // TODO add your handling code here:
        Dijkstra d = new Dijkstra(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_DijkstraActionPerformed

    private void NeurotrasmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeurotrasmisorActionPerformed
        // TODO add your handling code here:
        HashTable ht = new HashTable(grafo, hash);
        this.dispose();
    }//GEN-LAST:event_NeurotrasmisorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal(grafo, hash).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    private javax.swing.JButton Creacion_sinapsis;
    private javax.swing.JButton Dijkstra;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton MostrarHash;
    private javax.swing.JButton Mostrar_DFS_BFS;
    private javax.swing.JButton Neurotrasmisor;
    private javax.swing.JButton SimulacionDeFatiga;
    private javax.swing.JButton agregar_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
